### ISSUE TITLE
Main.overview.viewSelector is undefined

### ISSUE THREAD

**Issue by roryst** [diegonz/gnome-shell-extension-surf#1]
i get a "Main.overview.viewSelector is undefined" error enabling surf on fedora 35 with gnome 41.1

**Comment by diegonz** [comment]
Hi @rorymobley, I added support for _GNOME 40+_ in _version 2_, which I already submitted to extensions.gnome.org for review.
You can also install it from the `main` branch or [v2 tag](https://github.com/diegonz/gnome-shell-extension-surf/releases/tag/v2).

**Comment by diegonz** [comment]
[Version 2 has been published](https://extensions.gnome.org/extension/4661/surf/) on extensions.gnome.org.
