### ISSUE TITLE
GNOME 41 support :pray: 

### ISSUE THREAD

**Issue by martinpl** [diegonz/gnome-shell-extension-surf#2]

**Comment by diegonz** [comment]
I added support for _GNOME 40+_ in _version 2_, which I already submitted to extensions.gnome.org for review.
You can also install it from the `main` branch or [v2 tag](https://github.com/diegonz/gnome-shell-extension-surf/releases/tag/v2).

**Comment by martinpl** [comment]
Work, thanks! :)
